import{_ as r}from"./_plugin-vue_export-helper.cdc0426e.js";import{o as t,c as i,a as e,b as o,d as n,e as s,r as l}from"./app.59944050.js";const c="/assets/zookeeper-flink.0fba4d80.png",d="/assets/uuid.8b75bb93.png",h={},p=e("h1",{id:"zookeeper-问题",tabindex:"-1"},[e("a",{class:"header-anchor",href:"#zookeeper-问题","aria-hidden":"true"},"#"),o(" zookeeper 问题")],-1),u=e("ol",null,[e("li",null,[o("问题点"),e("img",{src:c,alt:"image"})]),e("li",null,"解决方案：不是 zookeeper 问题。 原因：因为在 flink 或 kafka 向 zookeeper 获取对应路径的时候，zookeeper 发现自身并没有创建这条路径，就会返回以上的错误。其实可以看到这条记录在 zookeeper 日志中是 INFO，并不是 error，所以对应的 flink 或 kafka 会过滤掉这些错误")],-1),_={href:"https://stackoverflow.com/questions/43559328/got-user-level-keeperexception-when-processing",target:"_blank",rel:"noopener noreferrer"},k=s('<h1 id="uuid-描述记录" tabindex="-1"><a class="header-anchor" href="#uuid-描述记录" aria-hidden="true">#</a> uuid 描述记录</h1><p><img src="'+d+'" alt="image"></p><h1 id="雪花算法原理" tabindex="-1"><a class="header-anchor" href="#雪花算法原理" aria-hidden="true">#</a> 雪花算法原理</h1><blockquote><p>雪花算法。基于 64bit 的 long 型的数字</p></blockquote><h2 id="构成" tabindex="-1"><a class="header-anchor" href="#构成" aria-hidden="true">#</a> 构成</h2><ul><li>1bit。无用</li><li>41bit。毫秒数【时间戳，2^41-1，即 69 年的时间】</li><li>10bit。工作机器 ID【5bit，机房 ID，2^5 个机房；5bit，机器 ID，2^5 个机器】</li><li>12bit。序列号【2^12-1】</li></ul>',6);function f(b,m){const a=l("ExternalLinkIcon");return t(),i("div",null,[p,u,e("p",null,[e("a",_,[o("stackoverflow 中的解答"),n(a)])]),k])}const z=r(h,[["render",f],["__file","index.html.vue"]]);export{z as default};
